### ISSUE TITLE
docker build failed 

### ISSUE THREAD

**Issue by pvssrikanth** [mbutkoviccinnamon/blog_fast_api#2]
Dear Sir,
while building image step 3 failing 

 ---> 639d924bfaba
Step 2/3 : COPY app.py db.py main.py models.py schema.py __init__.py requirements.txt .env ./app/
COPY failed: file not found in build context or excluded by .dockerignore: stat __init__.py: file does not exist

CAN YOU PELASE HELP where is this __init__.py file

OR AM I DOING WRONG IN COMMAND 
sudo docker build --tag fastapiblogapi .

Eagerly awaiting your reply

**Comment by pvssrikanth** [comment]
Dear Sir,
I removed __init__.py file and created image However while running getting error 

   tr, pr = await asyncio.wait_for(
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "uvloop/loop.pyx", line 1963, in create_connection
socket.gaierror: [Errno -2] Name or service not known

[2022-06-10 05:16:37 +0000] [301] [ERROR] Application startup failed. Exiting.
[2022-06-10 05:16:37 +0000] [301] [INFO] Worker exiting (pid: 301)
{"loglevel": "info", "workers": 8, "bind": "0.0.0.0:80", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "workers_per_core": 1.0, "use_max_workers": null, "host": "0.0.0.0", "port": "80"}
[2022-06-10 05:16:37 +0000] [312] [INFO] Started server process [312]
[2022-06-10 05:16:37 +0000] [312] [INFO] Waiting for application startup.
[2022-06-10 05:16:37 +0000] [311] [INFO] Started server process [311]
[2022-06-10 05:16:37 +0000] [311] [INFO] Waiting for application startup.
[2022-06-10 05:16:37 +0000] [312] [ERROR] Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 526, in lifespan
    async for item in self.lifespan_context(app):
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 467, in default_lifespan
    await self.startup()
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 502, in startup
    await handler()
  File "/app/app/app.py", line 10, in startup
    await db.connect()
  File "/usr/local/lib/python3.9/site-packages/databases/core.py", line 84, in connect
    await self._backend.connect()
  File "/usr/local/lib/python3.9/site-packages/databases/backends/postgres.py", line 66, in connect
    self._pool = await asyncpg.create_pool(
  File "/usr/local/lib/python3.9/site-packages/asyncpg/pool.py", line 398, in _async__init__
    await self._initialize()
  File "/usr/local/lib/python3.9/site-packages/asyncpg/pool.py", line 426, in _initialize
    await first_ch.connect()
  File "/usr/local/lib/python3.9/site-packages/asyncpg/pool.py", line 125, in connect
    self._con = await self._pool._get_new_connection()
  File "/usr/local/lib/python3.9/site-packages/asyncpg/pool.py", line 468, in _get_new_connection
    con = await connection.connect(
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connection.py", line 1718, in connect
    return await connect_utils._connect(
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 674, in _connect
    raise last_error
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 663, in _connect
    con = await _connect_addr(
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 632, in _connect_addr
    tr, pr = await asyncio.wait_for(
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "uvloop/loop.pyx", line 1963, in create_connection
socket.gaierror: [Errno -2] Name or service not known

[2022-06-10 05:16:37 +0000] [312] [ERROR] Application startup failed. Exiting.
[2022-06-10 05:16:37 +0000] [312] [INFO] Worker exiting (pid: 312)
{"loglevel": "info", "workers": 8, "bind": "0.0.0.0:80", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "workers_per_core": 1.0, "use_max_workers": null, "host": "0.0.0.0", "port": "80"}
[2022-06-10 05:16:37 +0000] [311] [ERROR] Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 526, in lifespan
    async for item in self.lifespan_context(app):
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 467, in default_lifespan
    await self.startup()
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 502, in startup
    await handler()
  File "/app/app/app.py", line 10, in startup
    await db.connect()
  File "/usr/local/lib/python3.9/site-packages/databases/core.py", line 84, in connect
    await self._backend.connect()
  File "/usr/local/lib/python3.9/site-packages/databases/backends/postgres.py", line 66, in connect
    self._pool = await asyncpg.create_pool(
  File "/usr/local/lib/python3.9/site-packages/asyncpg/pool.py", line 398, in _async__init__
    await self._initialize()
  File "/usr/local/lib/python3.9/site-packages/asyncpg/pool.py", line 426, in _initialize
    await first_ch.connect()
  File "/usr/local/lib/python3.9/site-packages/asyncpg/pool.py", line 125, in connect
    self._con = await self._pool._get_new_connection()
  File "/usr/local/lib/python3.9/site-packages/asyncpg/pool.py", line 468, in _get_new_connection
    con = await connection.connect(
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connection.py", line 1718, in connect
    return await connect_utils._connect(
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 674, in _connect
    raise last_error
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 663, in _connect
    con = await _connect_addr(
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 632, in _connect_addr
    tr, pr = await asyncio.wait_for(
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "uvloop/loop.pyx", line 1963, in create_connection
socket.gaierror: [Errno -2] Name or service not known

[2022-06-10 05:16:37 +0000] [311] [ERROR] Application startup failed. Exiting.
[2022-06-10 05:16:37 +0000] [311] [INFO] Worker exiting (pid: 311)
{"loglevel": "info", "workers": 8, "bind": "0.0.0.0:80", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "workers_per_core": 1.0, "use_max_workers": null, "host": "0.0.0.0", "port": "80"}
{"loglevel": "info", "workers": 8, "bind": "0.0.0.0:80", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "workers_per_core": 1.0, "use_max_workers": null, "host": "0.0.0.0", "port": "80"}
[2022-06-10 05:16:37 +0000] [1] [INFO] Shutting down: Master


Please guide at the earliest

Thanking you
srikanth

**Comment by pvssrikanth** [comment]
Dear Sir,
I am unable to build this docker image 

Please guide me how to build the image and run this

Thanks
